package test;

/**
 * "以下のような 800 文字の文字列がある。 ALPHABETLLABABBPLAALTABALATAALAALPAEPPAHABATALABLE
 * BLBEALBLPLBALLBLALPABBALEBALABELBLBHATAHLBAAEPLBAL
 * LLBBLBABEATLTTLBTBELBELAEHBBBLPALTPBLALBBHLBALLAHA
 * BEBLBABALAPLABBPPAHTBABLAALBEHABABLAAHLEABALTLBLLB
 * AAAAHBAHLPTBHTAEBTAABLATALLHEBETLBLALTBLABBABLBLAE
 * LBAABPAELAHPLBTPELBABLPBAABBBBPBBLLTLPLLBLPBTLBEBB
 * LTBBBLBTBEEBLAAABALLLAAAPLPAETPABAATBBLBABBBBPAEAA
 * ALAAHPBLLLBLATBHHBALTLLABBHLHLBPLLHBPLAHTHBALEBAAB
 * ABTBTATABBBALHAATAAPAHPBLALBEAEAAAALBBHBAHLPLBPELB
 * LHBBHLBEBHBEBALBEBLABTBETBBBBEATBTBPBAAABBBBLBLALL
 * AATELBTLPBTBBLPABABELLPLLLALAABLTBABBTAALELALAALAL
 * EAALBTLLALBTLAALLLLAAAALLBPEPLBALBAPBAATLAALLLLBLB
 * HTATATBALEBBPELLALBBLLLABBLABALHABBAATEALLAPBLAPAB
 * BLLLPAAAEAALAABLHTBLLAALHBBABPBBLHATLLAEPELAALLBBP
 * LLAALATBLALBAEALBTLBLATBPAAPPTLALBBLABTAAAAAALLLLA
 * BBALALABBLALLABEABAAAALTPBALLBPHHBBALBBTLABBAAAHAP
 *
 * <p>この文字列を 1 行 20 文字の形(全部で 40 行)に書き直したとする。 ※最初の 4 行のみを示す。 ALPHABETLLABABBPLAAL
 * TABALATAALAALPAEPPAH ABATALABLEBLBEALBLPL BALLBLALPABBA... 上から 2 行目の左から 5 文字目は「L」であり、そこから下方向に 3
 * 文字を読むと「LAB」となっている。 書き直した後の文字列全体で見たときに、下方向に 3 文字読むと「LAB」となっている箇所は全部でいくつあるか。
 */
public class p09_未解決 {
  public static void main(String[] args) {

  }

}
